#!/usr/bin/env python3
"""
BARKLY SEO WIRER

Automatically wires SEO.astro into every Astro page.

What it does:
- Recursively scans src/pages/
- Finds every .astro page
- Adds the correct relative SEO.astro import
- Adds <SEO /> inside <head>
- Removes old basic SEO tags that SEO.astro now owns
- Creates .bak backups before changing files
- Never duplicates the SEO import or component
- Supports nested Astro routes
- Uses Python standard library only

Usage:

    python barkly_seo.py

    python barkly_seo.py --project .

    python barkly_seo.py --project . --dry-run

    python barkly_seo.py --project . --no-backups
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path


SEO_MARKER = "SEO.astro"
SEO_COMPONENT = "<SEO />"


# ============================================================
# PROJECT DISCOVERY
# ============================================================


def find_project_root(start: Path) -> Path:
    """
    Find the nearest Astro project root.

    Looks for:
        astro.config.mjs
        astro.config.js
        astro.config.ts
    """

    start = start.resolve()

    for directory in [start, *start.parents]:

        if (
            (directory / "astro.config.mjs").exists()
            or (directory / "astro.config.js").exists()
            or (directory / "astro.config.ts").exists()
        ):
            return directory

    return start


# ============================================================
# IMPORT GENERATION
# ============================================================


def seo_import_for(
    page: Path,
    project_root: Path,
) -> str:
    """
    Generate the correct relative import for SEO.astro.

    Example:

        src/pages/about.astro

    becomes:

        import SEO from "../components/SEO.astro";
    """

    seo_file = (
        project_root
        / "src"
        / "components"
        / "SEO.astro"
    )

    relative = os.path.relpath(
        seo_file,
        start=page.parent,
    )

    import_path = Path(relative).as_posix()

    if not import_path.startswith("."):
        import_path = "./" + import_path

    return f'import SEO from "{import_path}";'


# ============================================================
# FRONTMATTER
# ============================================================


def add_import(
    content: str,
    import_line: str,
) -> tuple[str, bool]:
    """
    Add SEO import to Astro frontmatter.

    If frontmatter exists:

        ---
        existing code
        ---

    the import is inserted into it.

    If frontmatter does not exist,
    a new frontmatter block is created.
    """

    if SEO_MARKER in content:
        return content, False

    match = re.match(
        r"(?s)^(\s*---\s*\n)(.*?)(\n---\s*)",
        content,
    )

    if match:

        start, body, end = match.groups()

        new_body = (
            import_line
            + "\n"
            + body.lstrip("\n")
        )

        new_frontmatter = (
            start
            + new_body
            + end
        )

        content = (
            content[: match.start()]
            + new_frontmatter
            + content[match.end() :]
        )

        return content, True

    # No frontmatter.
    content = (
        "---\n"
        + import_line
        + "\n"
        + "---\n\n"
        + content.lstrip()
    )

    return content, True


# ============================================================
# OLD SEO REMOVAL
# ============================================================


def remove_existing_seo_tags(
    head: str,
) -> tuple[str, int]:
    """
    Remove SEO tags now generated by SEO.astro.

    This intentionally leaves unrelated <head> content alone.
    """

    patterns = [

        # ----------------------------------------------------
        # Title
        # ----------------------------------------------------

        r"<title\b[^>]*>.*?</title\s*>",

        # ----------------------------------------------------
        # Standard metadata
        # ----------------------------------------------------

        r'<meta\b[^>]*\bname=["\']description["\'][^>]*>',

        r'<meta\b[^>]*\bname=["\']robots["\'][^>]*>',

        # ----------------------------------------------------
        # Canonical
        # ----------------------------------------------------

        r'<link\b[^>]*\brel=["\']canonical["\'][^>]*>',

        # ----------------------------------------------------
        # Open Graph
        # ----------------------------------------------------

        r'<meta\b[^>]*\bproperty=["\']og:type["\'][^>]*>',

        r'<meta\b[^>]*\bproperty=["\']og:site_name["\'][^>]*>',

        r'<meta\b[^>]*\bproperty=["\']og:title["\'][^>]*>',

        r'<meta\b[^>]*\bproperty=["\']og:description["\'][^>]*>',

        r'<meta\b[^>]*\bproperty=["\']og:url["\'][^>]*>',

        # ----------------------------------------------------
        # Twitter / X
        # ----------------------------------------------------

        r'<meta\b[^>]*\bname=["\']twitter:card["\'][^>]*>',

        r'<meta\b[^>]*\bname=["\']twitter:title["\'][^>]*>',

        r'<meta\b[^>]*\bname=["\']twitter:description["\'][^>]*>',

        # ----------------------------------------------------
        # Theme
        # ----------------------------------------------------

        r'<meta\b[^>]*\bname=["\']theme-color["\'][^>]*>',

    ]

    removed = 0

    for pattern in patterns:

        head, count = re.subn(
            pattern,
            "",
            head,
            flags=re.IGNORECASE | re.DOTALL,
        )

        removed += count

    # Clean excessive blank lines.

    head = re.sub(
        r"\n[ \t]*\n[ \t]*\n+",
        "\n\n",
        head,
    )

    return head, removed


# ============================================================
# PAGE WIRING
# ============================================================


def wire_page(
    page: Path,
    project_root: Path,
    *,
    dry_run: bool,
    backups: bool,
) -> tuple[str, bool, str]:

    original = page.read_text(
        encoding="utf-8"
    )

    content = original

    # --------------------------------------------------------
    # Check existing SEO
    # --------------------------------------------------------

    has_component = bool(
        re.search(
            r"<SEO\s*/>",
            content,
            flags=re.IGNORECASE,
        )
    )

    has_import = SEO_MARKER in content

    # --------------------------------------------------------
    # Add import
    # --------------------------------------------------------

    if not has_import:

        import_line = seo_import_for(
            page,
            project_root,
        )

        content, _ = add_import(
            content,
            import_line,
        )

    # --------------------------------------------------------
    # Find <head>
    # --------------------------------------------------------

    head_match = re.search(
        r"<head\b[^>]*>(.*?)</head\s*>",
        content,
        flags=re.IGNORECASE | re.DOTALL,
    )

    if not head_match:

        return (
            "SKIP",
            False,
            "no <head>...</head> block found",
        )

    head = head_match.group(1)

    removed = 0

    # --------------------------------------------------------
    # Add SEO component
    # --------------------------------------------------------

    if not has_component:

        head, removed = remove_existing_seo_tags(
            head
        )

        # Put SEO after existing meta tags.

        meta_matches = list(
            re.finditer(
                r"<meta\b[^>]*>",
                head,
                flags=re.IGNORECASE,
            )
        )

        insertion = (
            "\n    "
            + SEO_COMPONENT
            + "\n"
        )

        if meta_matches:

            last_meta = meta_matches[-1]

            insert_at = last_meta.end()

            head = (
                head[:insert_at]
                + insertion
                + head[insert_at:]
            )

        else:

            head = (
                insertion
                + head
            )

    # --------------------------------------------------------
    # Reassemble document
    # --------------------------------------------------------

    new_content = (
        content[: head_match.start(1)]
        + head
        + content[head_match.end(1) :]
    )

    # --------------------------------------------------------
    # Nothing changed
    # --------------------------------------------------------

    if new_content == original:

        return (
            "OK",
            False,
            "already wired",
        )

    # --------------------------------------------------------
    # Dry run
    # --------------------------------------------------------

    if dry_run:

        detail = "would update"

        if removed:
            detail += (
                f", remove {removed} old SEO tag(s)"
            )

        return (
            "PLAN",
            True,
            detail,
        )

    # --------------------------------------------------------
    # Backup
    # --------------------------------------------------------

    if backups:

        backup = page.with_suffix(
            page.suffix + ".bak"
        )

        if not backup.exists():

            backup.write_text(
                original,
                encoding="utf-8",
            )

    # --------------------------------------------------------
    # Write
    # --------------------------------------------------------

    page.write_text(
        new_content,
        encoding="utf-8",
    )

    detail = "updated"

    if removed:

        detail += (
            f", removed {removed} old SEO tag(s)"
        )

    return (
        "UPDATED",
        True,
        detail,
    )


# ============================================================
# MAIN
# ============================================================


def main() -> int:

    parser = argparse.ArgumentParser(
        description=(
            "Automatically wire Barkly SEO.astro "
            "into every Astro page."
        )
    )

    parser.add_argument(
        "--project",
        type=Path,
        default=Path("."),
        help=(
            "Astro project directory "
            "(default: current directory)"
        ),
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Show what would change "
            "without modifying files."
        ),
    )

    parser.add_argument(
        "--no-backups",
        action="store_true",
        help="Do not create .bak files.",
    )

    args = parser.parse_args()

    # --------------------------------------------------------
    # Find project
    # --------------------------------------------------------

    project_root = find_project_root(
        args.project
    )

    pages_dir = (
        project_root
        / "src"
        / "pages"
    )

    seo_file = (
        project_root
        / "src"
        / "components"
        / "SEO.astro"
    )

    # --------------------------------------------------------
    # Header
    # --------------------------------------------------------

    print()
    print("BARKLY SEO WIRER")
    print("═" * 60)

    print(
        f"Project : {project_root}"
    )

    print(
        f"Pages   : {pages_dir}"
    )

    print(
        f"SEO     : {seo_file}"
    )

    print()

    # --------------------------------------------------------
    # Validation
    # --------------------------------------------------------

    if not pages_dir.exists():

        print(
            "ERROR: src/pages/ was not found."
        )

        return 1

    if not seo_file.exists():

        print(
            "ERROR: src/components/SEO.astro "
            "was not found."
        )

        print(
            "Create SEO.astro first."
        )

        return 1

    # --------------------------------------------------------
    # Find pages
    # --------------------------------------------------------

    pages = sorted(
        page
        for page in pages_dir.rglob(
            "*.astro"
        )
        if page.is_file()
    )

    if not pages:

        print(
            "ERROR: No Astro pages found."
        )

        return 1

    print(
        f"Found {len(pages)} Astro page(s)."
    )

    print()

    # --------------------------------------------------------
    # Statistics
    # --------------------------------------------------------

    updated = 0
    unchanged = 0
    skipped = 0
    errors = 0

    # --------------------------------------------------------
    # Process
    # --------------------------------------------------------

    for page in pages:

        relative = page.relative_to(
            project_root
        )

        try:

            status, changed, detail = wire_page(
                page,
                project_root,
                dry_run=args.dry_run,
                backups=not args.no_backups,
            )

        except Exception as exc:

            status = "ERROR"
            changed = False
            detail = str(exc)

        print(
            f"[{status:<7}] "
            f"{relative} — {detail}"
        )

        if status in {
            "UPDATED",
            "PLAN",
        }:

            updated += 1

        elif status == "OK":

            unchanged += 1

        elif status == "SKIP":

            skipped += 1

        else:

            errors += 1

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print()

    print("─" * 60)
    print("SEO PIPELINE COMPLETE")
    print("─" * 60)

    print(
        f"Pages scanned : {len(pages)}"
    )

    print(
        f"Updated       : {updated}"
    )

    print(
        f"Already wired : {unchanged}"
    )

    print(
        f"Skipped       : {skipped}"
    )

    print(
        f"Errors        : {errors}"
    )

    if args.dry_run:

        print()
        print(
            "DRY RUN: "
            "no files were modified."
        )

    if errors:

        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )